/**
 * FineSurE — Keyfact Extraction (no Task number; preparatory step for Task 2)
 *
 * Source:
 *   Paper Figure 5 (Appendix C). NOT included in the public utils.py.
 *
 * Paper:
 *   Song, H., Su, H., Shalyminov, I., Cai, J., Mansour, S. (2024).
 *   FineSurE: Fine-grained Summarization Evaluation using LLMs.
 *   arXiv:2407.00908v3. §3.4 + Appendix C Figure 5.
 *
 * Fidelity:
 *   Instruction text and few-shot examples reproduced VERBATIM from paper Figure 5.
 *   The JSON-format example in the original Figure 5 contains three lapsus that
 *   would propagate as malformed output to the LLM:
 *     - missing colon between "key facts" and the list,
 *     - plural "second key facts" / "third key facts" (each item is a single fact),
 *     - missing closing brace.
 *   These three lapsus are corrected below per the user-approved methodology
 *   note in the TCC §6.3. The algorithm, framework, instruction text,
 *   granularity examples and the 16-keyfact cap are preserved unchanged.
 *
 * Reference summary policy:
 *   Per paper §3.4 "Ideally, [keyfacts] should be generated by humans" and the
 *   Figure 5 input contract ("Given a reference summary"), the Summa pipeline
 *   passes the article's published abstract (written by the article authors)
 *   as the {summary} slot — preserving the human-written reference summary
 *   requirement without introducing an LLM-generated proxy.
 */

export interface KeyfactExtractionParseResult {
  keyfacts: string[];
}

/** Verbatim from paper Figure 5 with the three JSON example lapsus corrected. */
export function buildKeyfactExtractionPrompt(summary: string): string {
  return `
You will be provided with a summary. Your task is to decompose the summary into a set of "key facts". A "key fact" is a single fact written as briefly and clearly as possible, encompassing at most 2-3 entities.

Here are nine examples of key facts to illustrate the desired level of granularity:
* Kevin Carr set off on his journey from Haytor.
* Kevin Carr set off on his journey from Dartmoor.
* Kevin Carr set off on his journey in July 2013.
* Kevin Carr is less than 24 hours away from completing his trip.
* Kevin Carr ran around the world unsupported.
* Kevin Carr ran with his tent.
* Kevin Carr is set to break the previous record.
* Kevin Carr is set to break the record by 24 hours.
* The previous record was held by an Australian.

Instruction:
First, read the summary carefully.
Second, decompose the summary into (at most 16) key facts.

Provide your answer in JSON format. The answer should be a dictionary with the key "key facts" containing the key facts as a list:
{"key facts": ["first key fact", "second key fact", "third key fact"]}

Summary:
${summary}
`;
}

function sanitizeJsonish(raw: string): string {
  return raw
    .replace(/```json/g, '')
    .replace(/```/g, '')
    .replace(/'/g, '"')
    .replace(/,(\s*[\]\}])/g, '$1');
}

/**
 * Extracts the keyfact list. Tolerant of common LLM-output noise (code fences,
 * single quotes, trailing commas). Returns an empty list on unrecoverable
 * failure, mirroring the defensive style used in utils.py parsers.
 */
export function parseKeyfactExtractionOutput(output: string): KeyfactExtractionParseResult {
  try {
    const startObj = output.indexOf('{');
    const endObj = output.lastIndexOf('}');
    if (startObj === -1 || endObj === -1) {
      throw new Error('No JSON object found in keyfact extraction output');
    }
    const slice = sanitizeJsonish(output.slice(startObj, endObj + 1).replace(/\n/g, ''));
    const parsed = JSON.parse(slice) as { 'key facts'?: unknown };

    const raw = parsed['key facts'];
    if (!Array.isArray(raw)) {
      throw new Error('"key facts" field is not an array');
    }

    const keyfacts = raw
      .filter((k): k is string => typeof k === 'string')
      .map((k) => k.trim())
      .filter((k) => k.length > 0);

    return { keyfacts };
  } catch {
    return { keyfacts: [] };
  }
}
