import type { FactualityResult, ArticleStructure } from '@summarizer/shared';
import { generateCompletion } from './groqClient.js';
import {
  buildFactCheckingPrompt,
  parseFactCheckingOutput,
  computeFaithfulnessScore,
} from './finesure-prompts/factChecking.js';
import {
  buildKeyfactExtractionPrompt,
  parseKeyfactExtractionOutput,
} from './finesure-prompts/keyfactExtraction.js';
import {
  buildKeyfactAlignmentPrompt,
  parseKeyfactAlignmentOutput,
  computeCompletenessScore,
  computeConcisenessScore,
  type KeyfactAlignment,
} from './finesure-prompts/keyfactAlignment.js';

/**
 * FineSurE 3-dim factuality checker for Summa.
 *
 * Pipeline (Song et al. 2024, arXiv:2407.00908v3):
 *   - Task 1 (Fact Checking)     → faithfulness  (Eq. 1)
 *   - Keyfact Extraction (Fig 5) → list of K key facts from the article abstract
 *   - Task 2 (Keyfact Alignment) → completeness  (Eq. 2a)
 *                                 + conciseness  (Eq. 2b)
 *
 * Reference summary policy: per paper §3.4 ("ideally, [keyfacts] should be
 * generated by humans") and Figure 5 input contract ("Given a reference
 * summary"), the published abstract of the article is used as the reference
 * summary — see TCC §6.3 methodology note.
 *
 * Backbone is Llama 3.3 70B via Groq (consistent with summary generation,
 * matching the paper's Table 5 finding that Llama 3 70B-Instruct reaches
 * bACC ~92% on FRANK).
 *
 * This module replaces the legacy NLI two-pass + LLM-judge implementation
 * (still referenced as 'nli' / 'llm' / 'cap_exhausted' in historical
 * FactualityResult records).
 */

const FINESURE_MODEL = process.env.FINESURE_MODEL || 'llama-3.3-70b-versatile';
const FINESURE_TEMPERATURE = 0;
const FACT_CHECKING_MAX_TOKENS = 4000;
const KEYFACT_EXTRACTION_MAX_TOKENS = 1500;
const KEYFACT_ALIGNMENT_MAX_TOKENS = 2000;

// 9-category → 3-label UI mapping declared in TCC §4.5.
const CONTRADICTING_CATEGORIES = new Set([
  'out-of-context error',
  'entity error',
  'predicate error',
  'circumstantial error',
]);

const mapCategoryToLabel = (category: string): 'supported' | 'contradicted' | 'neutral' => {
  const normalized = category.toLowerCase().trim();
  if (normalized === 'no error') return 'supported';
  if (CONTRADICTING_CATEGORIES.has(normalized)) return 'contradicted';
  return 'neutral';
};

// ─── Sentence splitting ─────────────────────────────────────────────
// Not part of the FineSurE algorithm but required to feed `sentences` into
// the fact-checking prompt. Abbreviation-aware for PT/EN scientific prose
// so "Dr. Silva afirma..." or "Fig. 3 shows..." are not split mid-sentence.

const SENTENCE_ABBREVS = [
  'sr', 'sra', 'srta', 'dr', 'dra', 'prof', 'profa', 'eng', 'gen', 'cel',
  'fig', 'figs', 'tab', 'tabs', 'eq', 'eqs', 'ref', 'refs', 'cap', 'caps',
  'pg', 'pgs', 'p', 'pp', 'vol', 'no', 'etc', 'ed', 'eds', 'art', 'arts',
  'ex', 'i.e', 'e.g', 'cf', 'vs', 'ca',
];
const ABBREV_REGEX = new RegExp(`\\b(${SENTENCE_ABBREVS.join('|')})\\.`, 'gi');
const DOT_PLACEHOLDER = String.fromCharCode(1);

export const splitIntoSentences = (text: string): string[] => {
  const masked = text.replace(ABBREV_REGEX, (m) => m.replace('.', DOT_PLACEHOLDER));
  // Split at sentence boundaries (.!? followed by whitespace) OR at paragraph
  // breaks (blank line). The paragraph-break alternative prevents the splitter
  // from concatenating distinct markdown paragraphs (e.g. a bold header line
  // followed by content) into a single sentence — which would otherwise fail
  // to match the frontend's per-paragraph rendering.
  return masked
    .split(/(?<=[.!?])\s+|\n\s*\n/)
    .map((s) => s.replace(new RegExp(DOT_PLACEHOLDER, 'g'), '.').trim())
    .filter((s) => s.length > 0);
};

// ─── FineSurE pipeline pieces ───────────────────────────────────────

export interface FaithfulnessResult {
  predLabels: number[];
  predTypes: string[];
  reasons: string[];
  sentences: string[];
}

/** Task 1 — Fact Checking (Figure 3). Returns per-sentence category + reason + 0/1 label. */
export const checkFaithfulness = async (
  summarySentences: string[],
  articleText: string,
): Promise<FaithfulnessResult> => {
  if (summarySentences.length === 0) {
    return { predLabels: [], predTypes: [], reasons: [], sentences: [] };
  }
  const prompt = buildFactCheckingPrompt(articleText, summarySentences);
  const response = await generateCompletion({
    prompt,
    model: FINESURE_MODEL,
    temperature: FINESURE_TEMPERATURE,
    maxTokens: FACT_CHECKING_MAX_TOKENS,
  });
  return parseFactCheckingOutput(response);
};

/** Keyfact Extraction (Figure 5). Input must be a reference summary (the abstract). */
export const extractKeyfacts = async (referenceSummary: string): Promise<string[]> => {
  if (!referenceSummary.trim()) return [];
  const prompt = buildKeyfactExtractionPrompt(referenceSummary);
  const response = await generateCompletion({
    prompt,
    model: FINESURE_MODEL,
    temperature: FINESURE_TEMPERATURE,
    maxTokens: KEYFACT_EXTRACTION_MAX_TOKENS,
  });
  return parseKeyfactExtractionOutput(response).keyfacts;
};

export interface KeyfactAlignmentResult {
  predLabels: number[];
  matchedLines: number[];
  alignment: KeyfactAlignment[];
}

/** Task 2 — Keyfact Alignment (Figure 4). Returns per-keyfact 0/1 + matched summary line numbers + per-keyfact detail. */
export const alignKeyfacts = async (
  keyfacts: string[],
  summarySentences: string[],
): Promise<KeyfactAlignmentResult> => {
  if (keyfacts.length === 0 || summarySentences.length === 0) {
    return { predLabels: [], matchedLines: [], alignment: [] };
  }
  const prompt = buildKeyfactAlignmentPrompt(keyfacts, summarySentences);
  const response = await generateCompletion({
    prompt,
    model: FINESURE_MODEL,
    temperature: FINESURE_TEMPERATURE,
    maxTokens: KEYFACT_ALIGNMENT_MAX_TOKENS,
  });
  return parseKeyfactAlignmentOutput(response, keyfacts);
};

// ─── Public API ─────────────────────────────────────────────────────

export interface FineSurEScoreResult {
  /** Eq. 1 — faithfulness percentage. Null when no sentences were checked. */
  score: number | null;
  /** Per-sentence verdicts mapped to the 3-label UI palette. */
  results: FactualityResult[];
  /** Eq. 2a — completeness. Null when no abstract is available (no keyfact list extracted). */
  completeness: number | null;
  /** Eq. 2b — conciseness. Null when no abstract is available. */
  conciseness: number | null;
  /** The keyfact list extracted from the article abstract (empty when no abstract). */
  keyfacts: string[];
  /** Per-keyfact alignment detail (covered + which summary lines), empty when no abstract. */
  keyfactAlignment: KeyfactAlignment[];
}

/**
 * Run the full FineSurE 3-dim pipeline on a generated summary.
 *
 * The public signature is preserved from the legacy NLI+LLM-judge implementation
 * to keep `summarizationService.ts` and benchmark scripts working unchanged.
 * New return fields (`completeness`, `conciseness`, `keyfacts`) are additive;
 * existing callers that destructure only `{ score, results }` keep working.
 */
export const checkFactuality = async (
  summaryContent: string,
  articleStructure: ArticleStructure,
  rawText: string,
): Promise<FineSurEScoreResult> => {
  const sentences = splitIntoSentences(summaryContent);
  if (sentences.length === 0) {
    return { score: null, results: [], completeness: null, conciseness: null, keyfacts: [], keyfactAlignment: [] };
  }

  // Task 1 — Fact Checking against the raw article text.
  const faith = await checkFaithfulness(sentences, rawText);

  const results: FactualityResult[] = sentences.map((sentence, i) => {
    const category = faith.predTypes[i] ?? 'other error';
    return {
      sentence,
      label: mapCategoryToLabel(category),
      confidence: 1.0,
      category,
      rationale: faith.reasons[i] ?? '',
    };
  });
  const faithfulnessScore = faith.predLabels.length > 0
    ? computeFaithfulnessScore(faith.predLabels)
    : null;

  // Tasks 2a + 2b — Keyfact Extraction (from abstract) + Alignment.
  const abstract = articleStructure.abstract?.trim() ?? '';
  if (!abstract) {
    return {
      score: faithfulnessScore,
      results,
      completeness: null,
      conciseness: null,
      keyfacts: [],
      keyfactAlignment: [],
    };
  }

  const keyfacts = await extractKeyfacts(abstract);
  if (keyfacts.length === 0) {
    return {
      score: faithfulnessScore,
      results,
      completeness: null,
      conciseness: null,
      keyfacts: [],
      keyfactAlignment: [],
    };
  }

  const align = await alignKeyfacts(keyfacts, sentences);
  return {
    score: faithfulnessScore,
    results,
    completeness: computeCompletenessScore(align.predLabels),
    conciseness: computeConcisenessScore(align.matchedLines, sentences.length),
    keyfacts,
    keyfactAlignment: align.alignment,
  };
};

